#!/usr/bin/perl

use warnings;
use strict;

=begin comment

    randomstring.pl 1.0 - Prints a string generated by random. 

    Copyright (C) 2023 hlubenow

    This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

=end comment

=cut

my $NROFCHARS = 16;
if ($#ARGV >= 0 && $ARGV[0] !~ /\D/ && $ARGV[0] >= 1 && $ARGV[0] <= 100) {
    $NROFCHARS = $ARGV[0];
}

my ($i, $s, $ok, $r);

sub getRandomNumber {
    my ($f, $t) = @_;
    return int(rand($t - $f + 1)) + $f;
}

$s = "";
for $i (1 .. $NROFCHARS) {
    $ok = 0;
    while ($ok == 0) {
        # 122 (ASCII "z") - 48 (ASCII "A") + 1:
        $r = int(rand(75)) + 48;
        if ($r >= 58 && $r <= 64) {
            next;
        } 
        if ($r >= 91 && $r <= 96) {
            next;
        } 
        $s .= chr($r);
        $ok = 1;
    }
}

print "\n$s\n\n";
